# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2195cfe11a9bac1e2eec911847b34feee590901b86335a2e857de2f851529505b89af0726b11bcff9b3b4a9a5404f91753f9fc993b14f10c930b4a772b626c46

test:
  secret_key_base: df2c242715c0b670ec3f5a524614789abf3a99e62a89f04444c4da1117dfb4c4181e4249d7de3a7e63267d1e258a776c2c9119a1c6c5959ae71063e037ebbe04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
